# Generated by Django 3.1.4 on 2020-12-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='slusg',
            new_name='slug',
        ),
    ]
